gui:
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  theme:
    selectedLineBgColor:
      - '#252525' # set to `default` to have no background colour
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
keybinding:
  commits:
    moveDownCommit: '<c-n>' # changed from <c-j>
    moveUpCommit: '<c-p>'   # changed from <c-k>
